#!/usr/bin/env -S deno run --allow-read --allow-write
/**
 * Migration Assembly Script
 *
 * This script reads the SupaSaaSy configuration and assembles connector-specific
 * migrations into a single combined migration file. Only migrations for
 * configured connectors are included.
 *
 * Usage:
 *   deno run --allow-read --allow-write scripts/assemble-migrations.ts
 *
 * The script:
 * 1. Reads config/supasaasy.config.ts to identify configured connectors
 * 2. Scans each connector's migrations/ folder for SQL files
 * 3. Generates supabase/migrations/99999999999999_connector_migrations.sql
 */

import { join, dirname, fromFileUrl } from 'https://deno.land/std@0.208.0/path/mod.ts';
import { exists } from 'https://deno.land/std@0.208.0/fs/exists.ts';

// =============================================================================
// Configuration
// =============================================================================

const SCRIPT_DIR = dirname(fromFileUrl(import.meta.url));
const PROJECT_ROOT = join(SCRIPT_DIR, '..');
const CONFIG_PATH = join(PROJECT_ROOT, 'config', 'supasaasy.config.ts');
const CONNECTORS_DIR = join(PROJECT_ROOT, 'supabase', 'functions', '_shared', 'connectors');
const OUTPUT_PATH = join(PROJECT_ROOT, 'supabase', 'migrations', '99999999999999_connector_migrations.sql');

// =============================================================================
// Types
// =============================================================================

interface AppConfig {
  app_key: string;
  name: string;
  connector: string;
  config: Record<string, unknown>;
}

interface SupaSaaSyConfig {
  apps: AppConfig[];
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Extract unique connector names from the config
 */
function getConfiguredConnectors(config: SupaSaaSyConfig): string[] {
  const connectors = new Set<string>();
  for (const app of config.apps) {
    connectors.add(app.connector);
  }
  // Return sorted for deterministic output
  return Array.from(connectors).sort();
}

/**
 * Load the SupaSaaSy config file
 * Uses dynamic import to load the TypeScript config
 */
async function loadConfig(): Promise<SupaSaaSyConfig> {
  // Import the config module
  const configModule = await import(`file://${CONFIG_PATH}`);
  return configModule.default as SupaSaaSyConfig;
}

/**
 * Get migration files for a connector, sorted by filename
 */
async function getConnectorMigrations(connectorName: string): Promise<string[]> {
  const migrationsDir = join(CONNECTORS_DIR, connectorName, 'migrations');

  // Check if migrations directory exists
  if (!await exists(migrationsDir)) {
    console.log(`  No migrations directory for connector: ${connectorName}`);
    return [];
  }

  const files: string[] = [];
  for await (const entry of Deno.readDir(migrationsDir)) {
    if (entry.isFile && entry.name.endsWith('.sql')) {
      files.push(entry.name);
    }
  }

  // Sort by filename to ensure consistent order
  return files.sort();
}

/**
 * Read a migration file's content
 */
async function readMigrationFile(connectorName: string, filename: string): Promise<string> {
  const filepath = join(CONNECTORS_DIR, connectorName, 'migrations', filename);
  return await Deno.readTextFile(filepath);
}

/**
 * Generate the combined migration file header
 */
function generateHeader(connectors: string[]): string {
  const timestamp = new Date().toISOString();
  const connectorList = connectors.length > 0
    ? connectors.map(c => `--   - ${c}`).join('\n')
    : '--   (none)';

  return `-- ============================================================================
-- Combined Connector Migrations
-- ============================================================================
-- This file is auto-generated by scripts/assemble-migrations.ts
-- DO NOT EDIT MANUALLY - changes will be overwritten
--
-- Generated: ${timestamp}
-- Configured connectors:
${connectorList}
--
-- To regenerate this file, run:
--   deno run --allow-read --allow-write scripts/assemble-migrations.ts
-- ============================================================================

`;
}

/**
 * Generate a section header for a connector's migrations
 */
function generateConnectorHeader(connectorName: string): string {
  return `
-- ============================================================================
-- ${connectorName.toUpperCase()} CONNECTOR MIGRATIONS
-- ============================================================================

`;
}

/**
 * Generate a file header within a connector's section
 */
function generateFileHeader(connectorName: string, filename: string): string {
  return `-- ----------------------------------------------------------------------------
-- ${connectorName}/${filename}
-- ----------------------------------------------------------------------------

`;
}

// =============================================================================
// Main Assembly Logic
// =============================================================================

async function assembleMigrations(): Promise<void> {
  console.log('SupaSaaSy Migration Assembly');
  console.log('============================\n');

  // Load configuration
  console.log('Loading configuration...');
  let config: SupaSaaSyConfig;
  try {
    config = await loadConfig();
  } catch (error) {
    console.error(`Failed to load config: ${error}`);
    Deno.exit(1);
  }

  // Get configured connectors
  const connectors = getConfiguredConnectors(config);
  console.log(`Configured connectors: ${connectors.length > 0 ? connectors.join(', ') : '(none)'}\n`);

  // Start building the output
  let output = generateHeader(connectors);

  // Process each connector
  for (const connectorName of connectors) {
    console.log(`Processing connector: ${connectorName}`);

    const migrationFiles = await getConnectorMigrations(connectorName);

    if (migrationFiles.length === 0) {
      console.log(`  No migration files found\n`);
      continue;
    }

    console.log(`  Found ${migrationFiles.length} migration file(s): ${migrationFiles.join(', ')}`);

    output += generateConnectorHeader(connectorName);

    for (const filename of migrationFiles) {
      console.log(`  Assembling: ${filename}`);
      const content = await readMigrationFile(connectorName, filename);
      output += generateFileHeader(connectorName, filename);
      output += content;
      output += '\n';
    }

    console.log('');
  }

  // If no connectors configured, add a no-op statement
  if (connectors.length === 0) {
    output += `-- No connectors configured - this migration is a no-op
SELECT 1;
`;
  }

  // Write output file
  console.log(`Writing output to: ${OUTPUT_PATH}`);
  await Deno.writeTextFile(OUTPUT_PATH, output);

  console.log('\nMigration assembly complete!');

  // Summary
  console.log('\nSummary:');
  console.log(`  Connectors processed: ${connectors.length}`);
  console.log(`  Output file: supabase/migrations/99999999999999_connector_migrations.sql`);
}

// =============================================================================
// Entry Point
// =============================================================================

if (import.meta.main) {
  await assembleMigrations();
}
